version: "3.9"
services:
  idp:
    build:
      context: idp/
      args:
        SP_PORTS: "9443" # space separated for easy processing
    ports:
      - "8443:443"
  sp:
    build: sp/simple_php_website/
    ports:
      - "9443:443"
